spectaql:
  logoFile: ./src/public/logo.png

introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile:
    - src/typeDefs/agencies.graphql
    - src/typeDefs/agencyOfficers.graphql
    - src/typeDefs/airlines.graphql
    - src/typeDefs/airplane.graphql
    - src/typeDefs/auth.graphql
    - src/typeDefs/base.graphql
    - src/typeDefs/consignees.graphql
    - src/typeDefs/user.graphql
    - src/typeDefs/userArea.graphql
    - src/typeDefs/userRoles.graphql

info:
  title: GraphQL API Reference
  description: Documentation of the graphql API referring to the Group Transoceanica project
  termsOfService: https://www.initgrammers.com
  contact:
    name: API Support
    url: https://www.initgrammers.com
    email: info@initgrammers.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://initgrammers.com
    description: Production
    production: true